service: agent-platform-sequence-runner

provider:
  name: aws
  runtime: python3.13
  region: us-west-2
  environment:
    LANGSMITH_TRACING: ${env:LANGSMITH_TRACING}
    LANGSMITH_ENDPOINT: ${env:LANGSMITH_ENDPOINT}
    LANGSMITH_PROJECT: ${env:LANGSMITH_PROJECT}
    ENV: ${env:ENV}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource:
        - arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:secret:${env:ENV}/agent-platform-sequence-runner-*


functions:
  runSequence:
    handler: src.app.lambda_handler
    events:
      - http:
          path: process
          method: post

custom:
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - venv/**
    - tests/**
    - .venv/**
    - __pycache__/**
