service: mock-sequence-service

provider:
  name: aws
  runtime: python3.12
  region: us-west-2
  environment:
    PLATFORM_CONFIGS_URL: ${env:PLATFORM_CONFIGS_URL}
    OPENAI_API_KEY=: ${env:OPENAI_API_KEY}
    LANGSMITH_TRACING: ${env:LANGSMITH_TRACING}
    LANGSMITH_ENDPOINT: ${env:LANGSMITH_ENDPOINT}
    LANGSMITH_API_KEY: ${env:LANGSMITH_API_KEY}
    LANGSMITH_PROJECT: ${env:LANGSMITH_PROJECT}

functions:
  runSequence:
    handler: app.lambda_handler
    events:
      - http:
          path: process
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - venv/**
    - tests/**
    - .venv/**
    - __pycache__/**
